import 'package:flutter/material.dart';

const List<String> kAllInterests = [
  'Sport & Fitness', 'Musik', 'Gaming', 'Lesen', 'Kochen', 'Reisen',
  'Fotografie', 'Kunst', 'Film & Serien', 'Technologie', 'Natur', 'Mode',
  'Yoga', 'Tanzen', 'Wissenschaft', 'Geschichte', 'Sprachen', 'Tiere',
  'DIY', 'Finanzen', 'Politik', 'Philosophie', 'Familie', 'Ehrenamt',
  'Ernährung',
];

const Map<String, List<String>> kInterestCategories = {
  'Bewegung': ['Sport & Fitness', 'Yoga', 'Tanzen'],
  'Kreativität': ['Musik', 'Fotografie', 'Kunst', 'DIY', 'Mode'],
  'Unterhaltung': ['Gaming', 'Film & Serien', 'Lesen'],
  'Lifestyle': ['Kochen', 'Ernährung', 'Reisen', 'Natur', 'Tiere', 'Familie'],
  'Wissen': ['Technologie', 'Wissenschaft', 'Geschichte', 'Sprachen', 'Philosophie'],
  'Gesellschaft': ['Politik', 'Finanzen', 'Ehrenamt'],
};

const Map<String, IconData> kTagIcons = {
  'Sport & Fitness': Icons.directions_run,
  'Musik': Icons.music_note,
  'Gaming': Icons.sports_esports,
  'Lesen': Icons.menu_book,
  'Kochen': Icons.restaurant,
  'Reisen': Icons.flight,
  'Fotografie': Icons.camera_alt,
  'Kunst': Icons.brush,
  'Film & Serien': Icons.movie,
  'Technologie': Icons.computer,
  'Natur': Icons.park,
  'Mode': Icons.checkroom,
  'Yoga': Icons.self_improvement,
  'Tanzen': Icons.accessibility_new,
  'Wissenschaft': Icons.science,
  'Geschichte': Icons.history_edu,
  'Sprachen': Icons.translate,
  'Tiere': Icons.pets,
  'DIY': Icons.construction,
  'Finanzen': Icons.attach_money,
  'Politik': Icons.account_balance,
  'Philosophie': Icons.psychology,
  'Familie': Icons.family_restroom,
  'Ehrenamt': Icons.volunteer_activism,
  'Ernährung': Icons.restaurant_menu,
};

const Map<String, Color> kTagColors = {
  'Sport & Fitness': Color(0xFFFFE0B2),
  'Musik': Color(0xFFE8F5E9),
  'Gaming': Color(0xFFE3F2FD),
  'Lesen': Color(0xFFFCE4EC),
  'Kochen': Color(0xFFFFF8E1),
  'Reisen': Color(0xFFBBDEFB),
  'Fotografie': Color(0xFFF3E5F5),
  'Kunst': Color(0xFFFFEBEE),
  'Film & Serien': Color(0xFFE8EAF6),
  'Technologie': Color(0xFFE0F2F1),
  'Natur': Color(0xFFDCEDC8),
  'Mode': Color(0xFFFCE4EC),
  'Yoga': Color(0xFFEDE7F6),
  'Tanzen': Color(0xFFE0F2F1),
  'Wissenschaft': Color(0xFFE1F5FE),
  'Geschichte': Color(0xFFFFF3E0),
  'Sprachen': Color(0xFFE0F7FA),
  'Tiere': Color(0xFFFFF8E1),
  'DIY': Color(0xFFFBE9E7),
  'Finanzen': Color(0xFFE8F5E9),
  'Politik': Color(0xFFE3F2FD),
  'Philosophie': Color(0xFFEDE7F6),
  'Familie': Color(0xFFFCE4EC),
  'Ehrenamt': Color(0xFFD7F5D7),
  'Ernährung': Color(0xFFFFF9C4),
};
